// <auto-generated />
// This file was generated by a T4 template.
// Don't change it directly as your change would get overwritten.  Instead, make changes
// to the .tt file (i.e. the T4 template) and save it to regenerate this file.

// Make sure the compiler doesn't complain about missing Xml comments
#pragma warning disable 1591
#region T4MVC

using System;
using System.Diagnostics;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.CompilerServices;
using System.Threading.Tasks;
using System.Web;
using System.Web.Hosting;
using System.Web.Mvc;
using System.Web.Mvc.Ajax;
using System.Web.Mvc.Html;
using System.Web.Routing;
using T4MVC;
namespace RouteLocalization.Mvc.Sample.Controllers
{
    public partial class ControllerLevelAttributeController
    {
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ControllerLevelAttributeController() { }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected ControllerLevelAttributeController(Dummy d) { }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToAction(ActionResult result)
        {
            var callInfo = result.GetT4MVCResult();
            return RedirectToRoute(callInfo.RouteValueDictionary);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToAction(Task<ActionResult> taskResult)
        {
            return RedirectToAction(taskResult.Result);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToActionPermanent(ActionResult result)
        {
            var callInfo = result.GetT4MVCResult();
            return RedirectToRoutePermanent(callInfo.RouteValueDictionary);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToActionPermanent(Task<ActionResult> taskResult)
        {
            return RedirectToActionPermanent(taskResult.Result);
        }

        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult Book()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Book);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ControllerLevelAttributeController Actions { get { return MVC.ControllerLevelAttribute; } }
        [GeneratedCode("T4MVC", "2.0")]
        public readonly string Area = "";
        [GeneratedCode("T4MVC", "2.0")]
        public readonly string Name = "ControllerLevelAttribute";
        [GeneratedCode("T4MVC", "2.0")]
        public const string NameConst = "ControllerLevelAttribute";

        static readonly ActionNamesClass s_actions = new ActionNamesClass();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionNamesClass ActionNames { get { return s_actions; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionNamesClass
        {
            public readonly string Book = "Book";
            public readonly string Index = "Index";
            public readonly string Index2 = "Index2";
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionNameConstants
        {
            public const string Book = "Book";
            public const string Index = "Index";
            public const string Index2 = "Index2";
        }


        static readonly ActionParamsClass_Book s_params_Book = new ActionParamsClass_Book();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_Book BookParams { get { return s_params_Book; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_Book
        {
            public readonly string chapter = "chapter";
            public readonly string page = "page";
        }
        static readonly ViewsClass s_views = new ViewsClass();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ViewsClass Views { get { return s_views; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ViewsClass
        {
            static readonly _ViewNamesClass s_ViewNames = new _ViewNamesClass();
            public _ViewNamesClass ViewNames { get { return s_ViewNames; } }
            public class _ViewNamesClass
            {
                public readonly string Book = "Book";
                public readonly string Index = "Index";
                public readonly string Index2 = "Index2";
            }
            public readonly string Book = "~/Views/ControllerLevelAttribute/Book.cshtml";
            public readonly string Index = "~/Views/ControllerLevelAttribute/Index.cshtml";
            public readonly string Index2 = "~/Views/ControllerLevelAttribute/Index2.cshtml";
        }
    }

    [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
    public partial class T4MVC_ControllerLevelAttributeController : RouteLocalization.Mvc.Sample.Controllers.ControllerLevelAttributeController
    {
        public T4MVC_ControllerLevelAttributeController() : base(Dummy.Instance) { }

        [NonAction]
        partial void BookOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, int chapter, int page);

        [NonAction]
        public override System.Web.Mvc.ActionResult Book(int chapter, int page)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Book);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "chapter", chapter);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "page", page);
            BookOverride(callInfo, chapter, page);
            return callInfo;
        }

        [NonAction]
        partial void IndexOverride(T4MVC_System_Web_Mvc_ActionResult callInfo);

        [NonAction]
        public override System.Web.Mvc.ActionResult Index()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Index);
            IndexOverride(callInfo);
            return callInfo;
        }

        [NonAction]
        partial void Index2Override(T4MVC_System_Web_Mvc_ActionResult callInfo);

        [NonAction]
        public override System.Web.Mvc.ActionResult Index2()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Index2);
            Index2Override(callInfo);
            return callInfo;
        }

    }
}

#endregion T4MVC
#pragma warning restore 1591
